package tel.jeelpa.falsecaller.utils


// This code was generated by ChatGPT.
fun <T, K> Sequence<T>.distinctConsecutiveBy(selector: (T) -> K): Sequence<T> = sequence {
    var first = true
    var lastKey: K? = null

    for (item in this@distinctConsecutiveBy) {
        val key = selector(item)
        if (first || key != lastKey) {
            yield(item)
            lastKey = key
            first = false
        }
    }
}

fun <T> Sequence<T>.distinctConsecutive() = distinctConsecutiveBy { it }